<a href="https://colab.research.google.com/github/Dhanakumaripalepu/Dhanakumari_fmml_labs/blob/main/pythonbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to **Python**



## What is Python?
Python is a high-level, interpreted programming language known for its simplicity and readability. It was created by Guido van Rossum and first released in 1991. Python's design philosophy emphasizes code readability and simplicity, making it a popular choice for beginners and experienced developers alike.

## Key Features of Python
- **Easy to Learn and Use**: Python's syntax is straightforward, making it an excellent choice for beginners.
- **Interpreted Language**: Python code is executed line by line, which makes debugging easier.
- **Dynamically Typed**: You don't need to declare the type of variable when you write code. The interpreter infers the type at runtime.
- **Extensive Standard Library**: Python has a rich set of libraries and frameworks that support various applications.
- **Cross-Platform**: Python runs on various platforms, including Windows, macOS, and Linux.
- **Community Support**: Python has a large and active community that contributes to its development and provides support through forums and tutorials.

# What are Variables?
## Variables are containers for storing data values. In Python, you don’t need to declare a variable with a specific data type.



In [1]:
x = 5
name = "Alice"
is_active = True
# print(x) #Reassigning Variables
# x = 10
# print(x)

# IDENTIFIERS

## Rules for Identifiers in Python
- Must Begin with a Letter or an Underscore (_):

  An identifier can start with a letter (a-z, A-Z) or an underscore (_).
Examples: variable, _variable, Variable
- Followed by Letters, Digits, or Underscores:

  After the initial character, the identifier can contain letters, digits (0-9), or underscores.
Examples: var1, my_variable, var_2
- Case-Sensitive:

  Identifiers are case-sensitive, which means variable, Variable, and VARIABLE are different identifiers.
Examples: myVar, MyVar, myvar

- Cannot Be a Keyword:

  Identifiers cannot be the same as Python keywords. Keywords are reserved words in Python that have special meanings.
Examples of keywords: if, else, while, for, break, class, try, except, etc.

- No Special Characters Other Than Underscores:

  Identifiers cannot contain special characters like !, @, #, $, %, ^, &, *, -, +, etc.

  Invalid examples: my-var, var@name, name!

# KEY WORDS

## **False**: Boolean value indicating false.
## **None**: Represents the absence of a value.
## **True:** Boolean value indicating true.
## **and:** Logical operator that returns true if both operands are true.
## **as:** Used to create an alias while importing a module.
## **assert:** Used for debugging purposes to check if a condition is true.
## **async:** Declares an asynchronous function.
## **await:** Waits for the result of an async function.
## **break:** Terminates the nearest enclosing loop.
## **class:** Defines a new class.
## **continue:** Skips the rest of the code inside a loop for the current iteration only.
## **def:** Defines a new function.
## **del:** Deletes an object.
## **elif:** Else if condition, used in conditional statements.
## **else:** Used in conditional statements to provide an alternative block of code if the condition is false.
## **except:** Catches exceptions in a try block.
## **finally:** Executes code after try and except blocks, regardless of whether an exception was raised or not.
## **for**: Used to create a for loop.
## **from**: Imports specific parts of a module.
## **global**: Declares a global variable.
## **if**: Used to create a conditional statement.
## **import**: Imports a module.
## in: Checks if a value is present in a sequence (like a list, tuple, string, etc.).
## **is**: Tests object identity.
## **lambda**: Creates an anonymous function.
## **nonlocal**: Declares a non-local variable.
## **not**: Logical operator that returns true if the operand is false.
## **or**: Logical operator that returns true if at least one operand is true.
## **pass**: Does nothing, can be used as a placeholder.
## raise: Raises an exception.
## **return**: Exits a function and returns a value.
## **try**: Specifies a block of code to test for errors.
## **while**: Creates a while loop.
## **with**: Simplifies exception handling by encapsulating common preparation and cleanup tasks.
## **yield**: Used inside a function like a return statement, but returns a generator.

# COMMENTS

 Comments in Python are used to explain the code, make it more readable, and prevent execution of code. They are ignored by the Python interpreter, meaning they do not affect the execution of the program. There are two types of comments in Python: single-line comments and multi-line comments.Using Comments for Documentation
 Comments can also be used to provide documentation within your code, helping others understand what the code does, why certain decisions were made, or to mark sections of the code.

- **Single-Line Comments**:

Single-line comments start with a hash character (#) and extend to the end of the line. They are typically used for brief explanations or notes about the code.



In [2]:
# This is a single-line comment
print("Hello, World!")  # This is an inline comment


Hello, World!


- **Multi-Line Comments**:

Python does not have a specific syntax for multi-line comments like some other programming languages (e.g., /* ... */ in C/C++). Instead, multi-line comments are created by using multiple single-line comments or triple-quoted strings (which can also be used as docstrings, although docstrings are usually used to document functions, classes, and modules).

In [3]:
# This is a multi-line comment
# written using multiple
# single-line comments
print("Hello, World!")


Hello, World!


- **Using Triple-Quoted Strings**:

Triple-quoted strings (either ''' ... ''' or """ ... """) can be used to create multi-line comments. However, their primary use is for docstrings to document functions, classes, and modules.

In [4]:
"""
This is a multi-line comment.
It spans multiple lines.
Using triple-quoted strings.
"""
print("Hello, World!")


Hello, World!


# Python Data Types
- NUMERICAL
- SEQUENCE
- MAPPING
- SET
- BOOLEAN
-BINARY
-TEXT


## NUMERICAL:
### INTEGER
 Python has three main numerical data types: Integer, Float, and Complex.



In [5]:
age = 25
temperature = -5
count = 0
print(age, temperature, count)  # Output: 25 -5 0
print(type(age))


25 -5 0
<class 'int'>


### FLOAT
A float is a number that includes a decimal point. It represents real numbers and is used for precise calculations.

In [6]:
height = 5.9
pi = 3.14159
weight = 70.5
print(height, pi, weight)  # Output: 5.9 3.14159 70.5


5.9 3.14159 70.5


### Complex
A complex number consists of a real part and an imaginary part, represented as a + bj, where a is the real part and b is the imaginary part.

In [7]:
complex_number1 = 2 + 3j
complex_number2 = 1 - 4j
print(complex_number1, complex_number2)  # Output: (2+3j) (1-4j)


(2+3j) (1-4j)


## MAPPING:
In Python, the primary mapping data type is the dictionary. A dictionary is an unordered collection of key-value pairs. Each key-value pair maps the key to its associated value. Keys in a dictionary must be unique and immutable (e.g., strings, numbers, tuples), whereas values can be of any type and can be duplicated.
### Dictionary
Creating a Dictionary
You can create a dictionary using curly braces {} or the dict() function.


Some useful dictionary methods include:
- keys(): Returns a view object containing the keys of the dictionary.
- values(): Returns a view object containing the values of the dictionary.
- items(): Returns a view object containing the key-value pairs of the dictionary.

In [8]:
# Using curly braces
person = {
    "name": "Alice",
    "age": 30,
    "city": "New York"
}

# Using the dict() function
person = dict(name="Alice", age=30, city="New York")


# SEQUENCE
In Python, sequence data types are used to store collections of items in a specific order. The main sequence data types in Python are:

- List
- Tuple
- Range

##1. List

  A list is an ordered, mutable collection of items. Lists can contain items of different data types.


In [9]:
fruits = ["apple", "banana", "cherry"]
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", 3.14, True]


## 2. Tuple

  A tuple is an ordered, immutable collection of items. Once a tuple is created, you cannot change its values.

In [10]:
colors = ("red", "green", "blue")
coordinates = (10.0, 20.0)


## 3. Range:

  A range represents an immutable sequence of numbers and is often used for looping a specific number of times in for loops.

In [11]:
for i in range(5):
    print(i)  # Output: 0 1 2 3 4


0
1
2
3
4


List: Mutable, ordered collection of items.


Tuple: Immutable, ordered collection of items.


Range: Immutable sequence of numbers, often used in loops.


String: Immutable sequence of characters, used to store text.

## BOOLEAN
In Python, the Boolean data type is used to represent one of two values: True or False. Booleans are commonly used in conditional statements and control flow to determine the truthiness of an expression or variable.

In [12]:
is_sunny = True
is_raining = False
print(is_sunny)  # Output: True
print(is_raining)  # Output: False


True
False


# BINARY
In Python, binary data types are used to handle binary data, which is typically non-textual and consists of bytes. The main binary data types in Python are:

- bytes
- bytearray
- memoryview

In [13]:
b = b'Hello, World!'
print(b[0])    # Output: 72 (ASCII value of 'H')
print(b[1:5])  # Output: b'ello'


72
b'ello'


# SET
In Python, sets are unordered collections of unique elements.

There are two main set types:
- set
- frozenset.

## 1. set
A set is a mutable, unordered collection of unique elements. Sets are useful for membership testing, removing duplicates from a sequence, and mathematical operations like union, intersection, difference, and symmetric difference.

In [14]:
# Using curly braces
fruits = {"apple", "banana", "cherry"}
print(fruits)  # Output: {'apple', 'banana', 'cherry'}

# Using the set() constructor
numbers = set([1, 2, 3, 4, 4, 2])
print(numbers)  # Output: {1, 2, 3, 4}


{'cherry', 'banana', 'apple'}
{1, 2, 3, 4}


##2. frozenset
  
  
  A frozenset is an immutable version of a set. Once created, elements cannot be added or removed from a frozenset. It is useful when you need a set that should not change.

In [15]:
# Using frozenset() constructor
immutable_fruits = frozenset(["apple", "banana", "cherry"])
print(immutable_fruits)  # Output: frozenset({'apple', 'banana', 'cherry'})


frozenset({'cherry', 'banana', 'apple'})


# OPERATORS
Python has a variety of operators that are used to perform operations on variables and values

- Arithmetic
- Assignment
- Comparison
- Logic
- Identity
- Membership
- Bitwise

##1. Arithmetic Operators:
These operators are used to perform mathematical operations.

Addition


Subtraction


Multiplication


Division


Modulus

Exponentiation

Floor Division

In [16]:
a = 10
b = 3

print(a + b)   # Output: 13
print(a - b)   # Output: 7
print(a * b)   # Output: 30
print(a / b)   # Output: 3.3333333333333335
print(a % b)   # Output: 1
print(a ** b)  # Output: 1000
print(a // b)  # Output: 3


13
7
30
3.3333333333333335
1
1000
3


## 2. Comparison Operators:
These operators are used to compare two values and return a Boolean result.

== : Equal to


!= : Not equal to


(> ): Greater than


< : Less than


(>=): Greater than or equal to


<= : Less than or equal to

In [17]:
a = 10
b = 3

print(a == b)  # Output: False
print(a != b)  # Output: True
print(a > b)   # Output: True
print(a < b)   # Output: False
print(a >= b)  # Output: True
print(a <= b)  # Output: False


False
True
True
False
True
False


 ##3. Logical Operators:
These operators are used to perform logical operations and return a Boolean result.

and : Returns True if both statements are true


or : Returns True if one of the statements is true


not : Reverses the result, returns False if the result is true

In [18]:
x = True
y = False

print(x and y)  # Output: False
print(x or y)   # Output: True
print(not x)    # Output: False


False
True
False


## 4. Bitwise Operators:
These operators are used to perform bit-level operations on integers.

& : AND


| : OR


^ : XOR


~ : NOT


<< : Zero fill left shift


(>>) : Signed right shift

In [19]:
a = 10  # 1010 in binary
b = 4   # 0100 in binary

print(a & b)  # Output: 0
print(a | b)  # Output: 14
print(a ^ b)  # Output: 14
print(~a)     # Output: -11
print(a << 1) # Output: 20
print(a >> 1) # Output: 5


0
14
14
-11
20
5


## 5. Assignment Operators:
These operators are used to assign values to variables.

= : Assign


+= : Add and assign


-= : Subtract and assign


*= : Multiply and assign


/= : Divide and assign


%= : Modulus and assign


**= : Exponentiation and assign


//= : Floor division and assign

In [20]:
a = 10
a += 3  # Equivalent to a = a + 3
print(a)  # Output: 13

a -= 2  # Equivalent to a = a - 2
print(a)  # Output: 11

a *= 2  # Equivalent to a = a * 2
print(a)  # Output: 22

a /= 4  # Equivalent to a = a / 4
print(a)  # Output: 5.5

a %= 3  # Equivalent to a = a % 3
print(a)  # Output: 2.5

a **= 2  # Equivalent to a = a ** 2
print(a)  # Output: 6.25

a //= 2  # Equivalent to a = a // 2
print(a)  # Output: 3.0

13
11
22
5.5
2.5
6.25
3.0


## 6.membership Operators:
These operators are used to test if a sequence contains a value.

in : Returns True if a sequence with the specified value is present in the object


not in : Returns True if a sequence with the specified value is not present in the object

In [21]:
x = ["apple", "banana", "cherry"]

print("banana" in x)  # Output: True
print("mango" not in x)  # Output: True

True
True


## 7. Identity Operators:
These operators are used to compare the memory locations of two objects.

is : Returns True if both variables are the same object


is not : Returns True if both variables are not the same object

In [22]:
x = ["apple", "banana", "cherry"]
y = ["apple", "banana", "cherry"]
z = x

print(x is z)  # Output: True
print(x is y)  # Output: False
print(x == y)  # Output: True
print(x is not y)  # Output: True
print(x is not z)  # Output: False


True
False
True
True
False


# CONDITIONS

In Python, conditions are used to execute code based on whether certain criteria are met. This is typically done using if, elif, and else statements. You can also use conditional expressions and ternary operators for concise conditional logic. Here’s a comprehensive overview of different types of conditional constructs in Python:

## 1. if Statement:

  The if statement evaluates a condition and executes the block of code if the condition is True.

In [23]:
x = 10

if x > 5:
    print("x is greater than 5")


x is greater than 5


## 2. if-else Statement:

  The if-else statement provides an alternative block of code to execute if the condition is False.

In [24]:
x = 4

if x > 5:
    print("x is greater than 5")
else:
    print("x is not greater than 5")


x is not greater than 5


## 3. if-elif-else Statement:

  The if-elif-else statement allows you to check multiple conditions. It executes the block of code for the first condition that is True. If none of the conditions are True, it executes the else block.

In [25]:
x = 7

if x > 10:
    print("x is greater than 10")
elif x == 7:
    print("x is 7")
else:
    print("x is less than 10 and not 7")


x is 7


## 4. Nested if Statements:

  You can nest if statements within another if statement to check multiple conditions.

In [26]:
x = 15
y = 10

if x > 10:
    if y > 5:
        print("x is greater than 10 and y is greater than 5")
    else:
        print("x is greater than 10 but y is not greater than 5")
else:
    print("x is not greater than 10")


x is greater than 10 and y is greater than 5


**Summary:**


- if Statement: Executes a block of code if the condition is True.
- if-else Statement: Provides an alternative block of code if the condition is False.
- if-elif-else Statement: Checks multiple conditions in sequence.
- Nested if Statements: Used to check multiple conditions within each other.

## 5. Conditional Expressions (Ternary Operator)

### Conditional expressions allow you to evaluate conditions in a single line. This is useful for simple conditional assignments.

In [27]:
x = 6
result = "x is add" if x % 2 == 0 else "x is odd"
print(result)  # Output: x is odd

x is add


# LOOPS

### In Python, loops are used to execute a block of code repeatedly until a certain condition is met. There are two primary types of loops in Python: for loops and while loops. Each has its specific use cases and syntax.

- for loop
- while loop

**for loop**

### A for loop is used to iterate over a sequence (such as a list, tuple, string, or range) and execute a block of code for each element in the sequence.

## Syntax
### for i in range():


Using range() to generate a sequence of numbers


In [28]:
for i in range(5):
    print(i)

0
1
2
3
4


## while loop

A while loop repeatedly executes a block of code as long as a given condition is true.

## syntax

### while condition:



In [29]:
count = 0 #initilizing value
while count < 5:
    print(count)
    count += 1  #increment

0
1
2
3
4


# Functions


###In Python, you define functions using the def keyword followed by the function name, parentheses, and a colon. The body of the function is indented

### syntax
#### def function_name(parameters):

     <!-- Function body

     Optional return statement -->


In [30]:
def greet():
    print("Hello, world!")

greet()  # Output: Hello, world!


Hello, world!


In [31]:
def add(a, b):
    return a + b

result = add(3, 5)
print(result)  # Output: 8


8


# List Methods


append()-Adds an element at the end of the list


clear()-Removes all the elements from the list


copy()-Returns a copy of the list


count()-Returns the number of elements with the specified value


extend()-Add the elements of a list (or any iterable), to the end of the current list


index()-Returns the index of the first element with the specified value


insert()-Adds an element at the specified position

pop()-Removes the element at the specified position

remove()-Removes the item with the specified value

reverse()-Reverses the order of the list

sort()-Sorts the list

len()-Returns the number of elements in the list.

## append

In [32]:
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)  # Output: [1, 2, 3, 4]


[1, 2, 3, 4]


## extend

In [33]:
my_list = [1, 2, 3]
my_list.extend([4, 5])
print(my_list)  # Output: [1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]


## insert

In [34]:
my_list = [1, 2, 3]
my_list.insert(1, 'a')
print(my_list)  # Output: [1, 'a', 2, 3]


[1, 'a', 2, 3]


## remove

In [35]:
my_list = [1, 2, 3, 2]
my_list.remove(2)
print(my_list)  # Output: [1, 3, 2]


[1, 3, 2]


## pop

In [36]:
my_list = [1, 2, 3]
element = my_list.pop(1)
print(element)  # Output: 2
print(my_list)  # Output: [1, 3]


2
[1, 3]


## clear

In [37]:
my_list = [1, 2, 3]
my_list.clear()
print(my_list)  # Output: []


[]


## count

In [38]:
my_list = [1, 2, 3, 2]
count = my_list.count(2)
print(count)  # Output: 2


2


## sort

In [39]:
my_list = [3, 1, 4, 2]
my_list.sort()
print(my_list)  # Output: [1, 2, 3, 4]

# Sort in reverse order
my_list.sort(reverse=True)
print(my_list)  # Output: [4, 3, 2, 1]


[1, 2, 3, 4]
[4, 3, 2, 1]


## reverse

In [40]:
my_list = [1, 2, 3]
my_list.reverse()
print(my_list)  # Output: [3, 2, 1]


[3, 2, 1]


## length

In [41]:
my_list = [1, 2, 3]
length=len(my_list)
print(length) #output:3

3


# Insertion in list

- append(): Adds an element to the end of the list.
- insert(index, element): Inserts an element at a specified index.

# Deletion in list

- remove(element): Removes the first occurrence of a specified element.
- pop(index): Removes and returns the element at the specified index (default is the last element).
- clear(): Removes all elements from the list.

# set Methods

add()- Adds an element to the set.

remove()-Removes a specific element from the set. Raises a KeyError if the element is not found.

discard()-Removes a specific element from the set, but does not raise an error if the element is not found.

pop()-Removes and returns an arbitrary element from the set.

clear()-Removes all elements from the set.

union()-Returns a set containing all elements from both sets.

intersection()-Returns a set containing only elements that are common in both sets.


##Insertion

In [42]:
my_set = {1, 2, 3}
my_set.add(4)
print(my_set)  # Output: {1, 2, 3, 4}


{1, 2, 3, 4}


##Deletion

In [43]:
# Remove
my_set.remove(3)
print(my_set)  # Output: {1, 2, 4}

# Discard
my_set.discard(2)
print(my_set)  # Output: {1, 4}

# Pop
element = my_set.pop()
print(my_set)  # Output: {4}
print(element)  # Output: 1

# Clear
my_set.clear()
print(my_set)  # Output: set()


{1, 2, 4}
{1, 4}
{4}
1
set()


# Dictionary Methods



dict[key] = value-Adds a key-value pair to the dictionary.

pop(key)-Removes the key and returns its value.

del dict[key]-Deletes a key-value pair.

clear()-Removes all items from the dictionary.

keys()-Returns a view object of all the keys in the dictionary.

values()-Returns a view object of all the values in the dictionary.

items()-Returns a view object of all the key-value pairs in the dictionary.
python

copy()	Returns a copy of the dictionary

fromkeys()	Returns a dictionary with the specified keys and value

get()	Returns the value of the specified key

popitem()	Removes the last inserted key-value pair

##Inserting

In [44]:
my_dict = {'a': 1, 'b': 2}

# Insert
my_dict['c'] = 3
print(my_dict)  # Output: {'a': 1, 'b': 2, 'c': 3}


{'a': 1, 'b': 2, 'c': 3}


##Deleting

In [45]:
# Pop
value = my_dict.pop('b')
print(my_dict)  # Output: {'a': 1, 'c': 3}
print(value)  # Output: 2

# Delete
del my_dict['a']
print(my_dict)  # Output: {'c': 3}

# Clear
my_dict.clear()
print(my_dict)  # Output: {}


{'a': 1, 'c': 3}
2
{'c': 3}
{}


In [46]:
my_dict = {'a': 1, 'b': 2, 'c': 3}

# Keys
print(my_dict.keys())  # Output: dict_keys(['a', 'b', 'c'])

# Values
print(my_dict.values())  # Output: dict_values([1, 2, 3])

# Items
print(my_dict.items())  # Output: dict_items([('a', 1), ('b', 2), ('c', 3)])


dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])


##Tuples Methods

count()-Returns the number of times a specified value occurs in a tuple

index()-Searches the tuple for a specified value and returns the position of where it was found

In [47]:
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.count(5)

print(x)

2


In [48]:
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.index(8)

print(x)

3


# python libraries




1.Numpy

2.pandas

3.Matplotlib

4.Seaborn

5.Scikit-learn - data mining and data analysis.

# *Numpy Library*

numpy is a python library.


Numpy is used for working with arrays.

Numpy stands for "Numerical python".

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

installation of numpy is "pip install numpy"


# **Why we use numpy**

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray.

Arrays are very frequently used in data science.

# **Import NumPy**

import numpy or import numpy as np we use both import functions

In [49]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# **Numpy as np**



NumPy is usually imported under the np alias.

import numpy as np

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# **Create a NumPy ndarray Object**


We can create a NumPy ndarray object by using the array() function.

In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): This built-in Python function tells us the type of the object passed to it.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [52]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)
#using tuple

[1 2 3 4 5]


# Dimensions in Arrays

# 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [53]:
#Create a 0-D array with value 42
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

In [55]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## **3-D arrays**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [56]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# ***Numpy array indexing ***

# Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[1]+arr[2])

1
2
5


# **Access 2-D Arrays**
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.


In [58]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 2nd row: ', arr[0, 1])

2nd element on 2nd row:  2


In [59]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [60]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6



# **Negative Indexing**

Use negative indexing to access an array from the end.

In [61]:
#Print the last element from the 2nd dim:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# ***NumPy Array Slicing***

# Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1









In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [63]:
#Slice elements from index 4 to the end of the array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [64]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])



[1 2 3 4]


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
#
#Slice from the index 3 from the end to index 1 from the end:

[5 6]


In [66]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
#step

[2 4]


In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::1])
#Return every other element from the entire array:

[1 2 3 4 5 6 7]


# Slicing 2-d array


From the second element, slice elements from index 1 to index 4 (not included):

In [68]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


# Data Types in NumPy

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [69]:
#Get the data type of an array object:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [70]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)
#Get the data type of an array containing strings:

<U6


In [71]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)
#Create an array with data type string:

[b'1' b'2' b'3' b'4']
|S1


# NumPy Array Copy vs View

The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.



In [72]:
#Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [73]:
#example of view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Shape of an Array

The shape of an array is the number of elements in each dimension.

In [74]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)#Print the shape of a 2-D array:

(2, 4)


# NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

In [75]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Sorting Arrays

Sorting means putting elements in an ordered sequence.

In [76]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [77]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))#Sort the array alphabetically:

['apple' 'banana' 'cherry']


# ***Pandas ***

What is Pandas?

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

Installation of pandas is import pandas as pd

In [78]:

import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


# **What is a Series?**
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.

In [79]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


# Labels

If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

This label can be used to access a specified value.

In [80]:
print(myvar[0])#Return the first value of the Series:

1


# create Labels

With the index argument, you can name your own labels.


In [81]:
#Create your own labels:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)
print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


# Key/Value Objects as Series

You can also use a key/value object, like a dictionary, when creating a Series.

In [82]:
#create a simple Pandas Series from a dictionary:

import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [83]:
#Create a Series using only data from "day1" and "day2":

import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64


# **DataFrames**

Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table.

In [84]:
#Create a DataFrame from two Series:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


# What is a DataFrame?
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [85]:





#Create a simple Pandas DataFrame:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)
print(df.loc[0])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64


**Named Indexes**
With the index argument, you can name your own indexes.

# *Load Files Into a DataFrame*
If your data sets are stored in a file, Pandas can load them into a DataFrame.

In [86]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
#check the number of maximum returned rows:

import pandas as pd

print(pd.options.display.max_rows)

# Pandas - Analyzing DataFrames
# Viewing the Data
One of the most used method for getting a quick overview of the DataFrame, is the head() method.

The head() method returns the headers and a specified number of rows, starting from the top.

In [ ]:
#Get a quick overview by printing the first 10 rows of the DataFrame:

import pandas as pd

df = pd.read_csv('data.csv')

print(df.head(10))

There is also a tail() method for viewing the last rows of the DataFrame.

The tail() method returns the headers and a specified number of rows, starting from the bottom.

# **Info About the Data**
The DataFrames object has a method called info(), that gives you more information about the data set.



In [ ]:

#Print information about the data:

print(df.info())

# Data Cleaning

Data cleaning means fixing bad data in your data set.

Bad data could be:

Empty cells
Data in wrong format
Wrong data
Duplicates
In this tutorial you will learn how to deal with all of them.

